version: "3.8"
services:
  database:
    container_name: database
    image: mongo:5.0.9
    ports:
      - "27017"
  localstack:
    container_name: localstack
    image: localstack/localstack:1.4
    environment:
      - "DOCKER_HOST=unix:///var/run/docker.sock"
      - "HOSTNAME_EXTERNAL=localstack"
    volumes:
      - "./localstack-setup.sh:/etc/localstack/init/ready.d/localstack-setup.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566"
  users:
    container_name: users
    image: users:latest
    build:
      context: ./
      args:
        - module=users
    environment:
      - "AWS_ACCESS_KEY_ID=whatever"
      - "AWS_SECRET_KEY=whatever"
  orders-read-side:
    container_name: orders-read-side
    image: orders-read-side:latest
    build:
      context: ./
      args:
        - module=orders-read-side
    environment:
      - "AWS_ACCESS_KEY_ID=whatever"
      - "AWS_SECRET_KEY=whatever"
  orders-write-side:
    container_name: orders-write-side
    image: orders-write-side:latest
    build:
      context: ./
      args:
        - module=orders-write-side
    environment:
      - "AWS_ACCESS_KEY_ID=whatever"
      - "AWS_SECRET_KEY=whatever"
  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    build:
      context: ./
      args:
        - module=api-gateway
    ports:
      - "8080:8080"